const API_LOADING_START = 'API_LOADING_START';
const API_LOADING_SUCCESS = 'API_LOADING_SUCCESS';
const API_LOADING_FAILED = 'API_LOADING_FAILED';
const NULLIFY_ERROR = 'NULLIFY_ERROR';

const AUTH_SIGN = 'AUTH_SIGN';
const AUTH_LOGOUT = 'AUTH_LOGOUT';

const GET_CORONA = 'GET_CORONA';
const GET_COUNTRY_CORONA = 'GET_COUNTRY_CORONA';

export {
  API_LOADING_START,
  API_LOADING_FAILED,
  API_LOADING_SUCCESS,
  AUTH_LOGOUT,
  AUTH_SIGN,
  GET_CORONA,
  NULLIFY_ERROR,
  GET_COUNTRY_CORONA,
};
